title: Semantic Segmentation for Robot Navigation
description: Erika Jones, Nandini Ramakrishnan, Bruce Zheng
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false
